/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEventDialog: typeof import('./src/components/AddEventDialog.vue')['default']
    BookingCalendar: typeof import('./src/components/BookingCalendar.vue')['default']
    DeviceList: typeof import('./src/components/DeviceList.vue')['default']
    EditEventDialog: typeof import('./src/components/EditEventDialog.vue')['default']
    EventDetailDialog: typeof import('./src/components/EventDetailDialog.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavBarInstance: typeof import('./src/components/NavBarInstance.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Temp: typeof import('./src/components/Temp.vue')['default']
  }
}
